Made changes in HTTPS qualifier
kelloggm/https-checker pull request #2
Opened 2019-07-10 21:50 UTC by siddharthbe

2019-07-10 21:58 UTC, kelloggm requested changes
These are both reasonable changes, but they probably should have been in different pull requests, since they are unrelated. You also did not provide a justification for either in the public record. Finally, you should include at least one test case for your change to the defaulting rules. That test should fail with the old code, and pass with this change.

In general, the best practice when making a pull request is:
* make the pull request only do one, atomic thing. If it's possible to remove something from the PR and it still makes sense as a logical unit, do so, and make another pull request with that other thing.
* use the pull request description (which you left blank here) to justify why the PR is necessary, or what it improves.
* always include a test that fails before the PR and passes after, if at all possible

2019-07-11 16:58 UTC, siddharthbe commented
The HTTP checker was failing the LowerBoundTest case and hence necessary changes were made in HTTPS qualifier to pass the failing case.

2019-07-11 17:00 UTC, kelloggm requested changes
I don't see the need for a separate test runner for this test - I would just add it as another test under the https tests, since it's not that different. That will also make this PR smaller and simpler.

2019-07-11 17:00 UTC, kelloggm commented on src/test/java/tests/LowerBoundTest.java
> + * <p>The test data is located in the "tests/https" folder (by Checker Framework convention). If this test fails,
This comment isn't accurate

2019-07-11 17:05 UTC, siddharthbe commented on src/test/java/tests/LowerBoundTest.java
> + * <p>The test data is located in the "tests/https" folder (by Checker Framework convention). If this test fails,
Done

2019-07-11 17:15 UTC, kelloggm approved these changes
LGTM

2019-07-11 17:15 UTC, merged